name: Rust

on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latestj
    steps:
    - uses: actions/checkout@v3
    - name: Build debug
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --release
    - name: Upload release
      uses: actions/upload-artifact@v3.0.0
      with:
        name: statbat-release
        path: target/release/statbat
    - name: Run tests
      run: cargo test --release
